# Generated by Django 4.1.7 on 2023-02-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='data_inicio',
        ),
    ]
